query($formID: ID!){internalForm(id: $formID) {
      jsCode
    xmlCode
    id
    name
    description
    active
      teams {
    name
    id
  }
   schemas {
        edges {
          node {
            schema
            id
            key
          }
        }
      }
}}