query($formID: ID!)
{
  form(id: $formID) {
    jsCode
    xmlCode
    id
    name
    description
    active
     schemas {
        edges {
          node {
            schema
            id
            key
          }
        }
      }
  }
}